package com.entities;
// Generated 6 avr. 2018 18:17:58 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dayoff generated by hbm2java
 */
@Entity
@Table(name = "dayoff")
public class Dayoff{

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "day_off_id")
	private Integer day_off_id;
	
	@Column(name = "nursery_id")
	private Integer nursery_id;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "at_date")
	private Date at_date;
	
	@Column(name = "period_of_day")
	private String period_of_day;

	
	public Integer getDay_off_id() {
		return this.day_off_id;
	}

	public void setDay_off_id(Integer day_off_id) {
		this.day_off_id = day_off_id;
	}

	public Integer getNursery_id() {
		return this.nursery_id;
	}

	public void setNursery_id(Integer nursery_id) {
		this.nursery_id = nursery_id;
	}

	public Date getAt_date() {
		return this.at_date;
	}

	public void setAt_date(Date at_date) {
		this.at_date = at_date;
	}

	public String getPeriod_of_day() {
		return this.period_of_day;
	}

	public void setPeriod_of_day(String period_of_day) {
		this.period_of_day = period_of_day;
	}

}
