package com.entities;
// Generated 6 avr. 2018 18:17:58 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Nursery generated by hbm2java
 */
@Entity
@Table(name = "nursery", catalog = "nursery")
public class Nursery implements java.io.Serializable {

	private Integer nurseryId;
	private Integer maxNbChild;
	private Integer maxNbBaby;
	private Float pricePerHour;

	public Nursery() {
	}

	public Nursery(Integer maxNbChild, Integer maxNbBaby, Float pricePerHour) {
		this.maxNbChild = maxNbChild;
		this.maxNbBaby = maxNbBaby;
		this.pricePerHour = pricePerHour;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "nursery_id", unique = true, nullable = false)
	public Integer getNurseryId() {
		return this.nurseryId;
	}

	public void setNurseryId(Integer nurseryId) {
		this.nurseryId = nurseryId;
	}

	@Column(name = "max_nb_child")
	public Integer getMaxNbChild() {
		return this.maxNbChild;
	}

	public void setMaxNbChild(Integer maxNbChild) {
		this.maxNbChild = maxNbChild;
	}

	@Column(name = "max_nb_baby")
	public Integer getMaxNbBaby() {
		return this.maxNbBaby;
	}

	public void setMaxNbBaby(Integer maxNbBaby) {
		this.maxNbBaby = maxNbBaby;
	}

	@Column(name = "price_per_hour", precision = 12, scale = 0)
	public Float getPricePerHour() {
		return this.pricePerHour;
	}

	public void setPricePerHour(Float pricePerHour) {
		this.pricePerHour = pricePerHour;
	}

}
