package com.entities;
// Generated 6 avr. 2018 18:17:58 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name = "reservation")
public class Reservation{

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "reservation_id")
	private Integer reservation_id;
	
	@Column(name = "contract_id")
	private Integer contract_id;
	
	@Column(name = "absence")
	private Integer absence;
	
	@Column(name = "at_date")
	@Temporal(TemporalType.DATE)
	private Date at_date;
	
	@Column(name = "period_of_day")
	private String period_of_day;

	protected Reservation() { }
	
	public Reservation(Integer reservation_id, Integer contract_id, Integer absence, Date at_date, String period_of_day) {
		this.reservation_id = reservation_id;
		this.contract_id = contract_id;
		this.absence = absence;
		this.at_date = at_date;
		this.period_of_day = period_of_day;		
	}
	
	public Integer getReservation_id() {
		return this.reservation_id;
	}

	public void setReservation_id(Integer reservation_id) {
		this.reservation_id = reservation_id;
	}

	public Integer getContract_id() {
		return this.contract_id;
	}

	public void setContract_id(Integer contract_id) {
		this.contract_id = contract_id;
	}

	public Integer getAbsence() {
		return this.absence;
	}

	public void setAbsence(Integer absence) {
		this.absence = absence;
	}

	public Date getAt_date() {
		return this.at_date;
	}

	public void setAt_date(Date at_date) {
		this.at_date = at_date;
	}

	public String getPeriod_of_day() {
		return this.period_of_day;
	}

	public void setPeriod_of_day(String period_of_day) {
		this.period_of_day = period_of_day;
	}

}
