package com.entities;
// Generated 6 avr. 2018 18:17:58 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contract generated by hbm2java
 */
@Entity
@Table(name = "contract")
public class Contract{

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "contract_id")
	private Integer contract_id;
	
	@Column(name = "child_id")
	private Integer child_id;
	
	@Column(name = "is_regular")
	private Boolean is_regular;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "start_date")
	private Date start_date;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "end_date")
	private Date end_date;
	
	@Column(name = "email")
	private String email;
	
	@Column(name = "phone_nb")
	private String phone_nb;
	
	protected Contract() { }
	
	public Contract(Integer contract_id, Integer child_id, Boolean is_regular, Date start_date, Date end_date, String email, String phone_nb) {
		this.contract_id = contract_id;
		this.child_id = child_id;
		this.is_regular = is_regular;
		this.start_date = start_date;
		this.end_date = end_date;
		this.email = email;
		this.phone_nb = phone_nb;
	}

	
	public Integer getContract_id() {
		return this.contract_id;
	}

	public void setContract_id(Integer contract_id) {
		this.contract_id = contract_id;
	}
	
	public Integer getChild_id() {
		return this.child_id;
	}

	public void setChild_id(Integer child_id) {
		this.child_id = child_id;
	}
	
	public Boolean getIs_regular() {
		return this.is_regular;
	}

	public void setIs_regular(Boolean is_regular) {
		this.is_regular = is_regular;
	}

	public Date getStart_date() {
		return this.start_date;
	}

	public void setStart_date(Date start_date) {
		this.start_date = start_date;
	}

	public Date getEnd_date() {
		return this.end_date;
	}

	public void setEnd_date(Date end_date) {
		this.end_date = end_date;
	}
	
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone_nb() {
		return this.phone_nb;
	}

	public void setPhone_nb(String phone_nb) {
		this.phone_nb = phone_nb;
	}

}
