package com.entities;
// Generated 6 avr. 2018 17:17:51 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contract generated by hbm2java
 */
@Entity
@Table(name = "contract", catalog = "nursery")
public class Contract implements java.io.Serializable {

	private Integer contractId;
	private Integer childId;
	private Boolean isRegular;
	private Date startDate;
	private Date endDate;
	private String email;
	private String phoneNb;

	public Contract() {
	}

	public Contract(Integer childId, Boolean isRegular, Date startDate, Date endDate, String email, String phoneNb) {
		this.childId = childId;
		this.isRegular = isRegular;
		this.startDate = startDate;
		this.endDate = endDate;
		this.email = email;
		this.phoneNb = phoneNb;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "contract_id", unique = true, nullable = false)
	public Integer getContractId() {
		return this.contractId;
	}

	public void setContractId(Integer contractId) {
		this.contractId = contractId;
	}

	@Column(name = "child_id")
	public Integer getChildId() {
		return this.childId;
	}

	public void setChildId(Integer childId) {
		this.childId = childId;
	}

	@Column(name = "is_regular")
	public Boolean getIsRegular() {
		return this.isRegular;
	}

	public void setIsRegular(Boolean isRegular) {
		this.isRegular = isRegular;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "email", length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone_nb", length = 40)
	public String getPhoneNb() {
		return this.phoneNb;
	}

	public void setPhoneNb(String phoneNb) {
		this.phoneNb = phoneNb;
	}

}
