package com.entities;
// Generated 6 avr. 2018 18:11:36 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dayoff generated by hbm2java
 */
@Entity
@Table(name = "dayoff", catalog = "nursery")
public class Dayoff implements java.io.Serializable {

	private Integer dayOffId;
	private Integer nurseryId;
	private Date atDate;
	private String periodOfDay;

	public Dayoff() {
	}

	public Dayoff(Integer nurseryId, Date atDate, String periodOfDay) {
		this.nurseryId = nurseryId;
		this.atDate = atDate;
		this.periodOfDay = periodOfDay;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "day_off_id", unique = true, nullable = false)
	public Integer getDayOffId() {
		return this.dayOffId;
	}

	public void setDayOffId(Integer dayOffId) {
		this.dayOffId = dayOffId;
	}

	@Column(name = "nursery_id")
	public Integer getNurseryId() {
		return this.nurseryId;
	}

	public void setNurseryId(Integer nurseryId) {
		this.nurseryId = nurseryId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "at_date", length = 10)
	public Date getAtDate() {
		return this.atDate;
	}

	public void setAtDate(Date atDate) {
		this.atDate = atDate;
	}

	@Column(name = "period_of_day", length = 10)
	public String getPeriodOfDay() {
		return this.periodOfDay;
	}

	public void setPeriodOfDay(String periodOfDay) {
		this.periodOfDay = periodOfDay;
	}

}
