package com.entities;
// Generated 6 avr. 2018 18:17:58 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Nursery generated by hbm2java
 */
@Entity
@Table(name = "nursery")
public class Nursery{

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "nursery_id")
	private Integer nursery_id;
	
	@Column(name = "max_nb_child")
	private Integer max_nb_child;
	
	@Column(name = "max_nb_baby")
	private Integer max_nb_baby;
	
	@Column(name = "price_per_hour")
	private Float price_per_hour;
	
	public Integer getNursery_id() {
		return this.nursery_id;
	}

	public void setNursery_id(Integer nursery_id) {
		this.nursery_id = nursery_id;
	}

	public Integer getMax_nb_child() {
		return this.max_nb_child;
	}

	public void setMax_nb_child(Integer max_nb_child) {
		this.max_nb_child = max_nb_child;
	}
	
	public Integer getMax_nb_baby() {
		return this.max_nb_baby;
	}

	public void setMax_nb_baby(Integer max_nb_baby) {
		this.max_nb_baby = max_nb_baby;
	}

	
	public Float getPrice_per_hour() {
		return this.price_per_hour;
	}

	public void setPrice_per_hour(Float price_per_hour) {
		this.price_per_hour = price_per_hour;
	}

}
