package com.entities;
// Generated 6 avr. 2018 18:17:58 by Hibernate Tools 5.2.8.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Plannedabsence generated by hbm2java
 */
@Entity
@Table(name="plannedabsence"
    ,catalog="nursery"
)
public class Plannedabsence  implements java.io.Serializable {


     private Integer plannedAbsenceId;
     private Integer contractId;
     private Date atDate;
     private String periodOfDay;

    public Plannedabsence() {
    }

    public Plannedabsence(Integer contractId, Date atDate, String periodOfDay) {
       this.contractId = contractId;
       this.atDate = atDate;
       this.periodOfDay = periodOfDay;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="planned_absence_id", unique=true, nullable=false)
    public Integer getPlannedAbsenceId() {
        return this.plannedAbsenceId;
    }
    
    public void setPlannedAbsenceId(Integer plannedAbsenceId) {
        this.plannedAbsenceId = plannedAbsenceId;
    }

    
    @Column(name="contract_id")
    public Integer getContractId() {
        return this.contractId;
    }
    
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="at_date", length=10)
    public Date getAtDate() {
        return this.atDate;
    }
    
    public void setAtDate(Date atDate) {
        this.atDate = atDate;
    }

    
    @Column(name="period_of_day", length=10)
    public String getPeriodOfDay() {
        return this.periodOfDay;
    }
    
    public void setPeriodOfDay(String periodOfDay) {
        this.periodOfDay = periodOfDay;
    }




}


