package com.entities;
// Generated 6 avr. 2018 18:17:58 by Hibernate Tools 5.2.8.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Plannedabsence generated by hbm2java
 */
@Entity
@Table(name="plannedabsence")
public class Plannedabsence{

	@Id 
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="planned_absence_id")
    private Integer planned_absence_id;
	
	@Column(name="contract_id")
    private Integer contract_id;
	
	@Temporal(TemporalType.DATE)
    @Column(name="at_date", length=10)
    private Date at_date;
	
	@Column(name="period_of_day", length=10)
    private String period_of_day;
    
    public Integer getPlanned_absence_id() {
        return this.planned_absence_id;
    }
    
    public void setPlanned_absence_id(Integer planned_absence_id) {
        this.planned_absence_id = planned_absence_id;
    }

    public Integer getContract_id() {
        return this.contract_id;
    }
    
    public void setContract_id(Integer contract_id) {
        this.contract_id = contract_id;
    }

    public Date getAt_date() {
        return this.at_date;
    }
    
    public void setAt_date(Date at_date) {
        this.at_date = at_date;
    }
   
    public String getPeriod_of_day() {
        return this.period_of_day;
    }
    
    public void setPeriod_of_day(String period_of_day) {
        this.period_of_day = period_of_day;
    }

}


