package com.entities;
// Generated 6 avr. 2018 18:17:58 by Hibernate Tools 5.2.8.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Plannedabsence generated by hbm2java
 */
@Entity
@Table(name="plannedabsence")
public class Plannedabsence{

	@Id 
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="planned_absence_id")
    private Integer planned_absence_id;
	
	@Column(name="contract_id")
    private Integer contract_id;
	
	@Temporal(TemporalType.DATE)
    @Column(name="start_date", length=10)
    private Date start_date;
	
	@Temporal(TemporalType.DATE)
    @Column(name="end_date", length=10)
    private Date end_date;
	
	protected Plannedabsence() { }
	
	public Plannedabsence(Integer planned_absence_id, Integer contract_id, Date start_date, Date end_date) {
		this.planned_absence_id = planned_absence_id;
		this.contract_id = contract_id;
		this.start_date = start_date;
		this.end_date = end_date;
	}
    
    public Integer getPlanned_absence_id() {
        return this.planned_absence_id;
    }
    
    public void setPlanned_absence_id(Integer planned_absence_id) {
        this.planned_absence_id = planned_absence_id;
    }

    public Integer getContract_id() {
        return this.contract_id;
    }
    
    public void setContract_id(Integer contract_id) {
        this.contract_id = contract_id;
    }

    public Date getStart_date() {
        return this.start_date;
    }
    
    public void setStart_date(Date start_date) {
        this.start_date = start_date;
    }
    
    public Date getEnd_date() {
        return this.end_date;
    }
    
    public void setEnd_date(Date end_date) {
        this.end_date = end_date;
    }
   
    

}


